@use('App\Enums\TaskStatus')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks Report</title>
    <style>
        /* 1. Page & Typography Setup */
        @page {
            margin: 1cm 1.5cm;
            font-family: 'Helvetica', 'Arial', sans-serif;
        }

        body {
            color: #2D3748; /* Slate 800 */
            font-size: 12px;
            line-height: 1.5;
        }

        /* 2. Helper Classes */
        .text-right { text-align: right; }
        .text-bold { font-weight: bold; }
        .text-sm { font-size: 10px; }
        .text-uppercase { text-transform: uppercase; letter-spacing: 0.05em; }
        .text-subtle { color: #718096; } /* Slate 500 */
        
        /* 3. Header Layout (Using Table for robustness in DomPDF) */
        .header-table {
            width: 100%;
            margin-bottom: 25px;
            border-bottom: 2px solid #E2E8F0;
            padding-bottom: 15px;
        }
        .report-title {
            font-size: 20px;
            font-weight: 700;
            color: #1A202C;
            margin: 0;
        }

        /* 4. Summary Section */
        .summary-table {
            width: 100%;
            margin-bottom: 30px;
            background-color: #F7FAFC; /* Slate 50 */
            border-radius: 8px;
            padding: 15px;
        }
        .summary-label {
            font-size: 9px;
            color: #718096;
            text-transform: uppercase;
            margin-bottom: 4px;
        }
        .summary-value {
            font-size: 16px;
            font-weight: bold;
            color: #2D3748;
        }

        /* 5. Main Data Table */
        .data-table {
            width: 100%;
            border-collapse: collapse;
        }
        .data-table th {
            text-align: left;
            padding: 10px 12px;
            border-bottom: 2px solid #CBD5E0;
            font-size: 9px;
            text-transform: uppercase;
            color: #4A5568;
            font-weight: 600;
        }
        .data-table td {
            padding: 10px 12px;
            border-bottom: 1px solid #E2E8F0;
            vertical-align: middle;
        }
        .data-table tr:nth-child(even) {
            background-color: #F8FAFC;
        }
        /* No border for the last row */
        .data-table tr:last-child td {
            border-bottom: none;
        }

        /* 6. Badges & Status */
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 9999px; /* Pill shape */
            font-size: 9px;
            font-weight: 700;
            text-transform: uppercase;
        }
        /* Fallback badge color if dynamic color fails */
        .badge-default { background-color: #EDF2F7; color: #4A5568; }

        /* 7. Footer */
        .footer {
            position: fixed;
            bottom: -20px;
            left: 0;
            right: 0;
            font-size: 9px;
            color: #A0AEC0;
            text-align: center;
            border-top: 1px solid #E2E8F0;
            padding-top: 10px;
        }
    </style>
</head>
<body>

    <div class="footer">
        Confidential Report • Generated by {{ config('app.name') }} • Page <span class="page-number"></span>
    </div>

    <table class="header-table">
        <tr>
            <td valign="bottom">
                <h1 class="report-title">Tasks Report</h1>
                <div class="text-subtle text-sm">Project Management System</div>
            </td>
            <td valign="bottom" class="text-right">
                <div class="text-bold">Date:</div>
                <div class="text-sm text-subtle">{{ now()->format('M d, Y') }}</div>
                <div style="margin-top: 5px;"></div>
                <div class="text-bold">Generated by:</div>
                <div class="text-sm text-subtle">{{ auth()->user()->name ?? 'System' }}</div>
            </td>
        </tr>
    </table>

    <table class="summary-table">
        <tr>
            <td>
                <div class="summary-label">Total Tasks</div>
                <div class="summary-value">{{ $records->count() }}</div>
            </td>
            <td>
                <div class="summary-label">Open Tasks</div>
                <div class="summary-value">{{ $records->where('status.name', '!=', 'Completed')->count() }}</div>
            </td>
            <td>
                <div class="summary-label">Completion Rate</div>
                @php
                    $total = $records->count();
                    $completed = $records->where('status', TaskStatus::COMPLETED->value)->count();
                    $rate = $total > 0 ? round(($completed / $total) * 100) : 0;
                @endphp
                <div class="summary-value">{{ $rate }}%</div>
            </td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 25%;">Project</th>
                <th style="width: 30%;">Task Title</th>
                <th style="width: 15%;">Assigned To</th>
                <th style="width: 15%;">Due Date</th>
                <th style="width: 15%; text-align: right;">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $task)
            <tr>
                <td class="text-bold">
                    {{ $task->project->name ?? '—' }}
                </td>
                <td>
                    {{ $task->title }}
                    @if($task->description)
                        <br><span class="text-subtle text-sm">{{ Str::limit($task->description, 50) }}</span>
                    @endif
                </td>
                <td>
                    {{ $task->user->name ?? 'Unassigned' }}
                </td>
                <td>
                    @if($task->due_date)
                        <span class="{{ $task->due_date->isPast() && $task->status->name !== 'Completed' ? 'text-bold' : '' }}" 
                              style="color: {{ $task->due_date->isPast() && $task->status->name !== 'Completed' ? '#E53E3E' : 'inherit' }}">
                            {{ $task->due_date->format('M d, Y') }}
                        </span>
                    @else
                        <span class="text-subtle">—</span>
                    @endif
                </td>
                <td class="text-right">
                    <span class="badge" 
                          style="background-color: {{ $task->status->color ?? '#e2e8f0' }}; color: #fff; text-shadow: 0 1px 1px rgba(0,0,0,0.1);">
                        {{ $task->status }}
                    </span>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    @if($records->isEmpty())
        <div style="text-align: center; padding: 50px; color: #A0AEC0;">
            No tasks found for the selected criteria.
        </div>
    @endif

</body>
</html>