@use('App\Enums\TaskStatus')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks Report</title>
    <style>
        /* 1. Page & Typography Setup */
        @page {
            margin: 1cm 1.5cm;
            font-family: 'Helvetica', 'Arial', sans-serif;
        }

        body {
            color: #2D3748;
            font-size: 11px;
            line-height: 1.4;
        }

        /* 2. Helper Classes */
        .text-right { text-align: right; }
        .text-bold { font-weight: bold; }
        .text-sm { font-size: 9px; }
        .text-subtle { color: #718096; }
        .link-item { 
            color: #3182ce; 
            text-decoration: none; 
            margin-right: 8px;
            font-weight: bold;
        }

        /* 3. Layout Tables */
        .header-table, .summary-table, .data-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table {
            margin-bottom: 25px;
            border-bottom: 2px solid #E2E8F0;
            padding-bottom: 15px;
        }

        .report-title {
            font-size: 20px;
            font-weight: 700;
            color: #1A202C;
            margin: 0;
        }

        /* 4. Summary Section */
        .summary-table {
            margin-bottom: 30px;
            background-color: #F7FAFC;
            border-radius: 8px;
        }
        .summary-td { padding: 12px; text-align: center; }
        .summary-label { font-size: 8px; color: #718096; text-transform: uppercase; }
        .summary-value { font-size: 14px; font-weight: bold; }

        /* 5. Main Data Table */
        .data-table { table-layout: fixed; }
        .data-table th {
            text-align: left;
            padding: 10px 8px;
            border-bottom: 2px solid #CBD5E0;
            font-size: 9px;
            text-transform: uppercase;
            color: #4A5568;
        }
        .data-table td {
            padding: 10px 8px;
            border-bottom: 1px solid #E2E8F0;
            vertical-align: top;
        }
        .data-table tr:nth-child(even) { background-color: #F8FAFC; }

        /* 6. Badges */
        .badge {
            display: inline-block;
            padding: 3px 10px;
            border-radius: 10px;
            font-size: 8px;
            font-weight: 700;
            text-transform: uppercase;
            white-space: nowrap;
            color: #fff;
        }

        .footer {
            position: fixed;
            bottom: -15px;
            left: 0;
            right: 0;
            font-size: 9px;
            color: #A0AEC0;
            text-align: center;
        }
    </style>
</head>
<body>

    <div class="footer">
        Confidential Report • Generated by {{ config('app.name') }} • Page <span class="page-number"></span>
    </div>

    <table class="header-table">
        <tr>
            <td valign="bottom">
                <h1 class="report-title">Tasks Report</h1>
                <div style="margin-top: 5px; font-size: 14px;">
                    <span class="text-subtle">Project:</span> 
                    <span class="text-bold">{{ $records->first()?->project->name ?? 'N/A' }}</span>
                </div>
            </td>
            <td valign="bottom" class="text-right">
                <div class="text-bold">Date:</div>
                <div class="text-sm text-subtle">{{ now()->format('M d, Y') }}</div>
                <div style="margin-top: 5px;"></div>
                <div class="text-bold">Generated by:</div>
                <div class="text-sm text-subtle">{{ $user->name ?? 'System' }}</div>
            </td>
        </tr>
    </table>

    <table class="summary-table">
        <tr>
            <td class="summary-td">
                <div class="summary-label">Total Tasks</div>
                <div class="summary-value">{{ $records->count() }}</div>
            </td>
            <td class="summary-td" style="border-left: 1px solid #E2E8F0; border-right: 1px solid #E2E8F0;">
                <div class="summary-label">Open Tasks</div>
                <div class="summary-value">{{ $records->where('status', '!=', TaskStatus::COMPLETED->value)->count() }}</div>
            </td>
            <td class="summary-td">
                <div class="summary-label">Completion Rate</div>
                @php
                    $total = $records->count();
                    $completed = $records->where('status', TaskStatus::COMPLETED->value)->count();
                    $rate = $total > 0 ? round(($completed / $total) * 100) : 0;
                @endphp
                <div class="summary-value">{{ $rate }}%</div>
            </td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 35%;">Task Details</th>
                <th style="width: 13%;">Developer</th>
                <th style="width: 11%;">Start</th>
                <th style="width: 11%;">End</th>
                <th style="width: 11%;">Due</th>
                <th style="width: 19%; text-align: right;">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $task)
            @php
                $statusEnum = TaskStatus::tryFrom((string) $task->status);
            @endphp
            <tr>
                <td>
                    <div class="text-bold">{{ $task->title }}</div>
                    @if($task->description)
                        <div class="text-subtle text-sm" style="margin-bottom: 4px;">{{ Str::limit($task->description, 60) }}</div>
                    @endif
                    
                    @if(!empty($task->verification_links) && is_array($task->verification_links))
                        <div style="margin-top: 5px;">
                            @foreach($task->verification_links as $link)
                                @if(isset($link['url']))
                                    <a href="{{ $link['url'] }}" class="link-item text-sm">
                                        [ {{ $link['label'] ?? 'Link' }} ]
                                    </a>
                                @endif
                            @endforeach
                        </div>
                    @endif
                </td>
                <td>{{ $task->user->name ?? '—' }}</td>
                <td>{{ $task->start_date?->format('Y-m-d') ?? '—' }}</td>
                <td>{{ $task->end_date?->format('Y-m-d') ?? '—' }}</td>
                <td>
                    @if($task->due_date)
                        <span class="{{ $task->due_date->isPast() && $task->status !== TaskStatus::COMPLETED->value ? 'text-bold' : '' }}" 
                              style="color: {{ $task->due_date->isPast() && $task->status !== TaskStatus::COMPLETED->value ? '#E53E3E' : 'inherit' }}">
                            {{ $task->due_date->format('Y-m-d') }}
                        </span>
                    @else
                        <span class="text-subtle">—</span>
                    @endif
                </td>
                <td class="text-right">
                    <span class="badge" 
                          style="background-color: '#e2e8f0'; text-shadow: 0 1px 1px rgba(0,0,0,0.1);">
                        {{ str_replace('_', ' ', (string) $task->status) }}
                    </span>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    @if($records->isEmpty())
        <div style="text-align: center; padding: 50px; color: #A0AEC0;">
            No tasks found for the selected criteria.
        </div>
    @endif

</body>
</html>